[package]
name = "huggingcode-desktop"
version = "1.0.1"
description = "HuggingCode Desktop"
authors = ["Azurrchik"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.5.1", features = [] }

[dependencies]
serde_json = "1.0"
tauri = { version = "2.11.0", features = [] }
rfd = "0.15.4"
